### ISSUE TITLE
errors when installing for Apple Silicon - MacOS Ventura 13.6.2

### ISSUE THREAD

**Issue by opasquetdotfr** [TUD-STKS/VocalTractLab-dev#24]
Hello!

I am trying to install VocalTractLab on MacOS Ventura.
Apple Dev tools, XCode are installed.
Apple clang version 15.0.0 (clang-1500.0.40.1)

When trying 
`../configure --with-opengl`
as specified in your help.

Errors saved in "config.log" are:
conftest.c:11:10: fatal error: 'termio.h' file not found
_conftest.c:17:17: error: use of undeclared identifier 'choke'
conftest.c:11:10: fatal error: 'ac_nonexistent.h' file not found_

I am sure I am missing something super simple...

Thank you!

O.

**Comment by opasquetdotfr** [comment]
Hello,

FYI:
I made it work on Macos Sequoia 15.4.1.
I cannot tell you what I have done. But it works.
I installed [wxWidgets](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.8) 3.2.8.
I did not test OpenGL and the generation of the visual part.
